#ifndef HAND_HELD_ENV_MONITOR_H
#define HAND_HELD_ENV_MONITOR_H
#include"hand-held_environment_monitor.h"

#define MQ2_SENSOR_ANALOG_PIN 'A0'
#define HCHO_SENSOR_ANALOG_PIN 'A1'
#define AIRQ_SENSOR_ANALOG_PIN 'A2'

#define DHT_SENSOR_DIGITAL_PIN 2
#define DUST_SENSOR_DIGITAL_PIN 8

#define DUST_VALUE_INDEX 0
#define HCHO_VALUE_INDEX 1
#define AIRQ_VALUE_INDEX 2
#define CH4_VALUE_INDEX 3
#define TEMPERATURE_VALUE_INDEX 4
#define HUMIDITY_VALUE_INDEX 5

#define SENSOR_DUST_VALUE_INDEX "377545"//Dust
#define SENSOR_HCHO_VALUE_INDEX "377544"//HCHO
#define SENSOR_AIRQ_VALUE_INDEX "377542"//Air quality
#define SENSOR_CH4_VALUE_INDEX "377887"//CH4
#define SENSOR_TEMPERATURE_VALUE_INDEX "377543"//Temperature
#define SENSOR_HUMIDITY_VALUE_INDEX "377933" //Humidity

#endif

